### ISSUE TITLE
OnChange Triggered for Page refresh

### ISSUE THREAD

**Issue by edwardtew** [atikhono/defaultreviewers#3]
The DefaultReviewersHook is triggered for each page refresh in the Bitbucket Web UI even if there has not been any changes made to the PR.

With the DEBUG logging turned on:
curl -u admin:admin -v -X PUT -d "" -H "Content-Type: application/json" http://localhost:7990/bitbucket/rest/api/latest/logs/logger/com.parallels.bitbucket.plugins.defaultreviewers/debug

I see multiple entries in the atlassian-bitbucket.log that shows that the plugin is using git to check each file associated with the PR.

This process will add significant load to the Bitbucket server when large merge PRs are created.

Would it be possible to evaluate the cause of the event and avoid processing the PR if no updates have been made to the associated files.

**Comment by atikhono** [comment]
I agree it adds unnecessary load to the server and should be re-worked. The hook is triggered because it's implemented via an API which works that way.

Someone suggested me to implement a PluginSettings-driven hash map of tip SHAs for pull request source branches, and check actual tip SHA against the stored value every time a merge called. This should remove most of unwanted load.

Another solution would be to implement a PullRequestRescoped listener and parse only newly added commits. This should remove all unwanted load from the server. But with this implementation the plugin is not bound to the RepositoryHook API anymore, so it will lose its enable/disable button in Repository Settings/Hooks, and will be enabled by default for all repositories. To be able to turn it on for certain repositories I need to read on how to implement a plugin settings page.

**Comment by atikhono** [comment]
I've implemented the PluginSettings-based solution as described above. Released v1.0.1 (BBS 4.x) and v2.0.1 (BBS 5.1+) at the Marketplace.
